//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.17 at 08:11:26 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://thewally.nl/stub/manipulate/service/setresponse", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.thewally.stub.manipulate.service.setresponse;
